<?php

/**
 * @file
 * Code for the sn_audio feature.
 */

include_once 'sn_audio.features.inc';

/**
* Implements hook_ctools_plugin_directory().
*/
function sn_audio_ctools_plugin_directory($owner, $plugin_type) {
  if ($owner == 'ctools' && $plugin_type == 'content_types') {
    return 'plugins/' . $plugin_type;
  }
}

/**
 * Implement hook_theme().
 */
 function sn_audio_theme() {
   return array(
     'audio_player' => array(
       'template' => 'audio-player',
       'variables' => array('fid' => NULL, 'title' => NULL),
     ),
   );
 }

/**
 * Implement hook_preprocess_page().
 */
function sn_audio_preprocess_page(&$vars) {
  $module_path = drupal_get_path('module', 'sn_audio');
  drupal_add_js($module_path . '/js/sn-audio.js');
}

function sn_audio_form_alter(&$form, &$form_state, $form_id) {
  if (isset($form['#bundle']) && $form['#bundle'] == 'audio') {
    $form['field_audio_path']['#type'] = 'hidden';
    $form['field_itunes_duration']['#states'] = array(
      'visible' => array(
       ':input[name="field_audio_syndication[und]"]' => array('checked' => TRUE),
      ),
      'required' => array(
       ':input[name="field_audio_syndication[und]"]' => array('checked' => TRUE),
      ),
    );
    $form['field_itunes_summary']['#states'] = array(
      'visible' => array(
       ':input[name="field_audio_syndication[und]"]' => array('checked' => TRUE),
      ),
      'required' => array(
       ':input[name="field_audio_syndication[und]"]' => array('checked' => TRUE),
      ),
    );
    $form['field_itunes_subtitle']['#states'] = array(
      'visible' => array(
       ':input[name="field_audio_syndication[und]"]' => array('checked' => TRUE),
      ),
      'required' => array(
       ':input[name="field_audio_syndication[und]"]' => array('checked' => TRUE),
      ),
    );
    $form['field_itunes_explicit']['#states'] = array(
      'visible' => array(
       ':input[name="field_audio_syndication[und]"]' => array('checked' => TRUE),
      ),
      'required' => array(
       ':input[name="field_audio_syndication[und]"]' => array('checked' => TRUE),
      ),
    );
  }
}
